server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Routing Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy verso i microservizi backend
    location /api/auth/ {
        proxy_pass http://safeclaim-log-reg:6000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/assicurazione/ {
        proxy_pass http://safeclaim-assicurazione:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sinistri/ {
        proxy_pass http://safeclaim-sinistri:7000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/periti/ {
        proxy_pass http://safeclaim-periti:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/polizze/ {
        proxy_pass http://safeclaim-polizze:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/veicoli/ {
        proxy_pass http://safeclaim-veicoli:10000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/mail/ {
        proxy_pass http://safeclaim-mail:11000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/assistente/ {
        proxy_pass http://safeclaim-rag:12000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}